### ISSUE TITLE
Unleash your robot on UW 2560x1080

### ISSUE THREAD

**Issue by RobinOpletal** [pop-os/wallpapers#8]
The background doesn't really fit, I don't know how important such screen resolution is to you 

![image](https://user-images.githubusercontent.com/49439044/79696091-cde24300-827a-11ea-9518-d86018e3ce59.png)

**Comment by leviport** [comment]
It looks like you're using an ultrawide monitor, so you may have to change the scaling mode in gnome-tweaks -> Appearance -> Background -> Adjustment. The default wallpapers were designed with a roughly 16:9 aspect ratio in mind.
